<a href="https://colab.research.google.com/github/Lucas-Bas/Aluraplus/blob/main/Aula05_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np

# Define the number of rows
num_rows = 50

# Generate sample data for each column
produtos = [f'Produto_{i}' for i in range(num_rows)]
categorias = np.random.choice(['Eletrônicos', 'Roupas', 'Alimentos', 'Livros', 'Casa'], num_rows)
precos = np.round(np.random.uniform(10.0, 500.0, num_rows), 2) # Prices between 10.0 and 500.0
avaliacoes = np.round(np.random.uniform(1.0, 5.0, num_rows), 1) # Ratings between 1.0 and 5.0
quantidades_vendidas = np.random.randint(1, 100, num_rows) # Quantities between 1 and 100

# Create a dictionary from the data
data = {
    'produto': produtos,
    'categoria': categorias,
    'preço': precos,
    'avaliação': avaliacoes,
    'quantidade_vendida': quantidades_vendidas
}

# Create the DataFrame
df_produtos = pd.DataFrame(data)

# Display the first 5 rows of the DataFrame
display(df.head())

     produto categoria   preço  avaliação  quantidade_vendida
0  Produto_0    Roupas  145.28        4.4                  56
1  Produto_1    Livros   74.22        4.0                  59
2  Produto_2    Livros  189.95        2.4                  10
3  Produto_3      Casa  239.70        2.9                  53
4  Produto_4    Livros  395.40        2.3                  49

In [10]:
df_produtos

       produto    categoria   preço  avaliação  quantidade_vendida
0    Produto_0    Alimentos   32.19        2.5                  33
1    Produto_1  Eletrônicos   99.16        3.9                  79
2    Produto_2         Casa  247.06        2.2                  63
3    Produto_3  Eletrônicos  435.38        2.7                  49
4    Produto_4       Livros  401.52        4.9                  21
5    Produto_5       Livros  336.36        3.8                   3
6    Produto_6    Alimentos  437.50        1.8                  47
7    Produto_7       Livros  370.50        5.0                  51
8    Produto_8       Roupas  267.11        1.6                  64
9    Produto_9       Roupas  131.73        2.8                  23
10  Produto_10         Casa  431.83        2.5                  79
11  Produto_11  Eletrônicos  110.77        1.9                  30
12  Produto_12    Alimentos  337.39        3.0                  78
13  Produto_13         Casa  229.00        1.7                  91
14  Produto_14         Casa  288.52        2.8                  64
15  Produto_15       Roupas  151.18        4.8                  96
16  Produto_16       Livros  295.56        4.4                  90
17  Produto_17         Casa  416.62        4.8                  24
18  Produto_18       Roupas  164.89        3.9                  83
19  Produto_19  Eletrônicos  476.30        4.1                  89
20  Produto_20    Alimentos  399.98        1.1                  72
21  Produto_21    Alimentos   98.01        3.9                  64
22  Produto_22    Alimentos   35.43        2.7                  87
23  Produto_23       Livros   29.38        1.5                  76
24  Produto_24       Roupas  161.85        2.7                  82
25  Produto_25         Casa  189.65        4.7                  78
26  Produto_26    Alimentos   78.19        4.6                  90
27  Produto_27    Alimentos   26.43        4.1                  40
28  Produto_28         Casa  387.86        4.5                  71
29  Produto_29       Roupas   26.61        3.0                  72
30  Produto_30  Eletrônicos  143.37        1.3                  43
31  Produto_31         Casa  276.90        2.3                  28
32  Produto_32  Eletrônicos  491.79        2.1                  42
33  Produto_33    Alimentos  112.93        2.8                   9
34  Produto_34       Roupas  492.74        3.5                  92
35  Produto_35         Casa  315.51        1.0                  98
36  Produto_36  Eletrônicos  400.60        3.2                  83
37  Produto_37    Alimentos  107.32        3.8                   5
38  Produto_38       Roupas   82.22        2.5                   1
39  Produto_39       Livros   93.44        4.2                  17
40  Produto_40         Casa  414.29        4.9                  72
41  Produto_41         Casa  410.38        4.9                  34
42  Produto_42         Casa  209.93        3.1                  70
43  Produto_43       Roupas  339.03        3.9                  84
44  Produto_44         Casa  191.06        4.8                   9
45  Produto_45       Livros  290.45        1.4                  85
46  Produto_46       Roupas  231.23        1.3                  94
47  Produto_47    Alimentos  106.67        2.7                  19
48  Produto_48         Casa  333.85        2.9                  22
49  Produto_49       Livros   66.55        3.2                  93

In [11]:
df_produtos['categoria']

0       Alimentos
1     Eletrônicos
2            Casa
3     Eletrônicos
4          Livros
5          Livros
6       Alimentos
7          Livros
8          Roupas
9          Roupas
10           Casa
11    Eletrônicos
12      Alimentos
13           Casa
14           Casa
15         Roupas
16         Livros
17           Casa
18         Roupas
19    Eletrônicos
20      Alimentos
21      Alimentos
22      Alimentos
23         Livros
24         Roupas
25           Casa
26      Alimentos
27      Alimentos
28           Casa
29         Roupas
30    Eletrônicos
31           Casa
32    Eletrônicos
33      Alimentos
34         Roupas
35           Casa
36    Eletrônicos
37      Alimentos
38         Roupas
39         Livros
40           Casa
41           Casa
42           Casa
43         Roupas
44           Casa
45         Livros
46         Roupas
47      Alimentos
48           Casa
49         Livros
Name: categoria, dtype: object

In [12]:
df_produtos['categoria'].unique()

array(['Alimentos', 'Eletrônicos', 'Casa', 'Livros', 'Roupas'],
      dtype=object)

In [13]:
set(df_produtos['categoria'])

{'Alimentos', 'Casa', 'Eletrônicos', 'Livros', 'Roupas'}

Filtrando elementos de um Dataframe Pandas

In [16]:
df_produtos['categoria'] == 'Eletrônicos'

0     False
1      True
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19     True
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30     True
31    False
32     True
33    False
34    False
35    False
36     True
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
Name: categoria, dtype: bool

In [14]:
df_produtos[df_produtos['categoria'] == 'Eletrônicos']

       produto    categoria   preço  avaliação  quantidade_vendida
1    Produto_1  Eletrônicos   99.16        3.9                  79
3    Produto_3  Eletrônicos  435.38        2.7                  49
11  Produto_11  Eletrônicos  110.77        1.9                  30
19  Produto_19  Eletrônicos  476.30        4.1                  89
30  Produto_30  Eletrônicos  143.37        1.3                  43
32  Produto_32  Eletrônicos  491.79        2.1                  42
36  Produto_36  Eletrônicos  400.60        3.2                  83

In [18]:
df_produtos[df_produtos['avaliação'] < 2.0]

       produto    categoria   preço  avaliação  quantidade_vendida
6    Produto_6    Alimentos  437.50        1.8                  47
8    Produto_8       Roupas  267.11        1.6                  64
11  Produto_11  Eletrônicos  110.77        1.9                  30
13  Produto_13         Casa  229.00        1.7                  91
20  Produto_20    Alimentos  399.98        1.1                  72
23  Produto_23       Livros   29.38        1.5                  76
30  Produto_30  Eletrônicos  143.37        1.3                  43
35  Produto_35         Casa  315.51        1.0                  98
45  Produto_45       Livros  290.45        1.4                  85
46  Produto_46       Roupas  231.23        1.3                  94

In [19]:
df_produtos.shape

(50, 5)

In [20]:
df_produtos_fitro_avaliacao_monor_que_2 = df_produtos[df_produtos['avaliação'] < 2.0]

In [21]:
print(df_produtos_fitro_avaliacao_monor_que_2)

       produto    categoria   preço  avaliação  quantidade_vendida
6    Produto_6    Alimentos  437.50        1.8                  47
8    Produto_8       Roupas  267.11        1.6                  64
11  Produto_11  Eletrônicos  110.77        1.9                  30
13  Produto_13         Casa  229.00        1.7                  91
20  Produto_20    Alimentos  399.98        1.1                  72
23  Produto_23       Livros   29.38        1.5                  76
30  Produto_30  Eletrônicos  143.37        1.3                  43
35  Produto_35         Casa  315.51        1.0                  98
45  Produto_45       Livros  290.45        1.4                  85
46  Produto_46       Roupas  231.23        1.3                  94

In [23]:
df_produtos_fitro_avaliacao_monor_que_2.shape

(10, 5)

In [24]:
df_produtos[(df_produtos['categoria'] == 'Eletrônicos') & (df_produtos['preço'] >= 350.0)]

       produto    categoria   preço  avaliação  quantidade_vendida
3    Produto_3  Eletrônicos  435.38        2.7                  49
19  Produto_19  Eletrônicos  476.30        4.1                  89
32  Produto_32  Eletrônicos  491.79        2.1                  42
36  Produto_36  Eletrônicos  400.60        3.2                  83