<a href="https://colab.research.google.com/github/Lucas-Bas/Aluraplus/blob/main/Aula06_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
dados = {'Produto': ['Produto A', 'Produto B', 'Produto C'],
         'Preço': [100, 150, 200],
         'Estoque': [30, 20, 50]}
df = pd.DataFrame(dados)

In [ ]:
df

     Produto  Preço  Estoque
0  Produto A    100       30
1  Produto B    150       20
2  Produto C    200       50

In [ ]:
# Transformando a coluna 'Produto' em índice
df_indexado = df.set_index('Produto')
print(df_indexado)

           Preço  Estoque
Produto
Produto A    100       30
Produto B    150       20
Produto C    200       50

In [7]:
try:
    pegando_algo = int(input("Digite a sua idade:"))

    magica = 25/pegando_algo
    print(magica)
except ValueError:
    print("Você não digitou um número inteiro válido")
except ValueError as ve:
    print("Você não digitou um número inteiro válido")
    print("Detalhes do erro:", ve)
except ValueError:
    print("Você não digitou um número inteiro válido")
except TypeError:
    print("Você não pode somar um número inteiro com uma string")
except Exception as e:
    print("Detalhes do erro:", e)
finally:
    print("Finalizei o processo")

Digite a sua idade:a
Você não digitou um número inteiro válido
Finalizei o processo

In [2]:
pip install ollama pandas

Collecting ollama
  Downloading ollama-0.6.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: httpx>=0.27 in /usr/local/lib/python3.13/dist-packages (from ollama) (0.28.1)
Requirement already satisfied: pydantic>=2.9 in /usr/local/lib/python3.13/dist-packages (from ollama) (2.13.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27->ollama) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27->ollama) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27->ollama) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx>=0.27->ollama) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx>=0.27->ollama) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.9->ollama) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.9->ollama) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.9->ollama) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.9->ollama) (0.4.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading ollama-0.6.2-py3-none-any.whl (15 kB)
Installing collected packages: ollama
Successfully installed ollama-0.6.2

In [3]:
!pip install -q -U google-genai

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 kB 971.5 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 21.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.7/259.7 kB 10.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires google-auth==2.49.0, but you have google-auth 2.57.0 which is incompatible.

In [4]:

# Importações
import pandas as pd
import re
from google import genai
from google.colab import userdata, files

In [5]:
# Lê sua chave salva nos Secrets do Colab
GEMINI_API_KEY = userdata.get("GeminiAPIKeyAulaPy04")

# Conecta ao Gemini
client = genai.Client(api_key=GEMINI_API_KEY)

In [13]:



# Lê o arquivo com 13 avaliações
df_reviews = pd.read_csv("/Dados/reviews_13_exemplos.csv")

# Junta todas as avaliações para enviar em UMA requisição
avaliacoes = "\n\n".join(
    f"{i + 1}. {texto}"
    for i, texto in enumerate(df_reviews["reviewText"])
)

# Instrução para a IA
prompt = f"""
Classifique cada avaliação como Positiva, Negativa ou Neutra.

Responda exatamente uma classificação por linha, na mesma ordem
das avaliações. Não explique, não numere e não escreva mais nada.

Avaliações:
{avaliacoes}
"""

# Faz somente uma chamada para a IA
resposta = client.models.generate_content(
    model="gemini-3.6-flash",
    contents=prompt
)

# Extrai somente Positiva, Negativa ou Neutra da resposta
classificacoes = re.findall(
    r"\b(positiva|negativa|neutra)\b",
    resposta.text,
    flags=re.IGNORECASE
)

classificacoes = [item.capitalize() for item in classificacoes]

# Confere se a IA classificou todas as 13 avaliações
if len(classificacoes) != len(df_reviews):
    print(resposta.text)
    raise ValueError(
        f"Foram encontradas {len(classificacoes)} classificações, "
        f"mas existem {len(df_reviews)} avaliações."
    )

# Cria a nova coluna e salva o arquivo final
df_reviews["classificacao_ia"] = classificacoes

caminho_saida = "/Dados/reviews_13_com_respostas.csv"

df_reviews.to_csv(
    caminho_saida,
    index=False,
    encoding="utf-8-sig"
)

# Mostra o resultado
display(df_reviews[["reviewText", "classificacao_ia"]])

# Baixa o arquivo para seu computador
files.download(caminho_saida)

print("Concluído!")

WARNING:google_genai.models:Direct use of automatic function calling (AFC) in Models.generate_content is not recommended. Instead, we recommend to use AFC in Chat.send_message. Similarly, direct use of AFC in Models.generate_content_stream is not recommended. Instead, we recommend to use AFC in Chat.send_message_stream.

                                           reviewText classificacao_ia
0   it works as expected. I should have sprung for...           Neutra
1   This think has worked out great.Had a diff. br...         Positiva
2   Bought it with Retail Packaging, arrived legit...         Positiva
3   It's mini storage.  It doesn't do anything els...         Positiva
4   I have it in my phone and it never skips a bea...         Positiva
5   It works, but file writes are a bit slower tha...           Neutra
6   I bought 2 of those SanDisk 32 GB microSD , us...         Negativa
7   The memory card is an excellent condition and ...         Positiva
8   I bougth this micro SD card after some trubles...         Negativa
9   Ordered this for a Galaxy S3.  Lasted a few mo...         Negativa
10  more like 8mb/s in my Note 10.1 and that's usi...           Neutra
11  I used this for a few months in my phone, then...         Negativa
12  everything about it was great, except for the ...         Positiva

Concluído!

In [14]:
df_reviews.head(13)

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote,classificacao_ia
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0,Neutra
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0,Positiva
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0,Positiva
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0,Positiva
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0,Positiva
5,A2Q3ICGWZLY3JJ,B007WTAJTO,98020,"It works, but file writes are a bit slower tha...",1384905600,20/11/2013,383,0,0,Neutra
6,AF24M1HKIZ7QC,B007WTAJTO,"Abdulrahman J. Alrashed ""dr34m3r""","I bought 2 of those SanDisk 32 GB microSD , us...",1375488000,08/03/2013,640,0,0,Negativa
7,A1KIF9Z5VFPH7H,B007WTAJTO,"Abel Feliciano ""Ace Master""",The memory card is an excellent condition and ...,1347321600,09/11/2012,759,0,0,Positiva
8,A1FKE13D77L3Y3,B007WTAJTO,Abraham Arturo Meza Marin,I bougth this micro SD card after some trubles...,1361232000,19/02/2013,657,0,0,Negativa
9,A1X1FX3NSOFCT3,B007WTAJTO,"Abused Commuter ""abused_commuter""",Ordered this for a Galaxy S3. Lasted a few mo...,1374278400,20/07/2013,506,0,1,Negativa
10,A3RV1L35IPTV61,B007WTAJTO,abushaheed,more like 8mb/s in my Note 10.1 and that's usi...,1357430400,01/06/2013,555,0,0,Neutra
11,A2RJ7DAL63MN1F,B007WTAJTO,Ace of Sevens,"I used this for a few months in my phone, then...",1391126400,31/01/2014,311,0,0,Negativa
12,A3IJIFZ5HH819V,B007WTAJTO,A. Cho,"everything about it was great, except for the ...",1373414400,07/10/2013,427,0,0,Positiva

In [15]:
coluna_de_reviews = df_reviews ['reviewText']
coluna_de_reviews

0     it works as expected. I should have sprung for...
1     This think has worked out great.Had a diff. br...
2     Bought it with Retail Packaging, arrived legit...
3     It's mini storage.  It doesn't do anything els...
4     I have it in my phone and it never skips a bea...
5     It works, but file writes are a bit slower tha...
6     I bought 2 of those SanDisk 32 GB microSD , us...
7     The memory card is an excellent condition and ...
8     I bougth this micro SD card after some trubles...
9     Ordered this for a Galaxy S3.  Lasted a few mo...
10    more like 8mb/s in my Note 10.1 and that's usi...
11    I used this for a few months in my phone, then...
12    everything about it was great, except for the ...
Name: reviewText, dtype: object

In [16]:
df_reviews[df_reviews["classificacao_ia"] == 'Negativa']

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote,classificacao_ia
6,AF24M1HKIZ7QC,B007WTAJTO,"Abdulrahman J. Alrashed ""dr34m3r""","I bought 2 of those SanDisk 32 GB microSD , us...",1375488000,08/03/2013,640,0,0,Negativa
8,A1FKE13D77L3Y3,B007WTAJTO,Abraham Arturo Meza Marin,I bougth this micro SD card after some trubles...,1361232000,19/02/2013,657,0,0,Negativa
9,A1X1FX3NSOFCT3,B007WTAJTO,"Abused Commuter ""abused_commuter""",Ordered this for a Galaxy S3. Lasted a few mo...,1374278400,20/07/2013,506,0,1,Negativa
11,A2RJ7DAL63MN1F,B007WTAJTO,Ace of Sevens,"I used this for a few months in my phone, then...",1391126400,31/01/2014,311,0,0,Negativa