<a href="https://colab.research.google.com/github/Lucas-Bas/Aluraplus/blob/main/Pandas_limpeza_e_tratamento_de_dados2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import json

In [3]:
with open('/content/drive/MyDrive/Estudar/Pandas: limpeza e tratamento de dados/cursos_cadastrados.json', 'r') as f:
  data = json.load(f)

In [5]:
# normaliza o json
df = pd.json_normalize(data)

In [6]:
# exibe o DataFrame resultante
print(df)

                             curso      categoria carga_horaria concluintes  \
0         Introdução à programação    Programação      20 horas         100
1            Excel para iniciantes  Produtividade          None        None
2  Marketing digital para negócios      Marketing      30 horas          75
3          Inteligência artificial    Programação      40 horas
4             Inglês para negócios        Idiomas      20 horas          30
5         Introdução à programação    Programação      20 horas         100

  data_inicio data_conclusao  \
0  2022-01-01     2022-01-20
1        None           None
2  2022-03-01     2022-03-31
3  2022-04-01
4
5  2022-01-01     2022-01-20

                                           descricao  preco  instrutor.nome  \
0        Curso introdutório à programação com Python  99.90      João Silva
1                                               None   None  Maria Oliveira
2                    Curso introdutório em marketing   89.9      Ana Santos
3  Curso avançado sobre inteligência artificial c...  129.9
4                      Curso de inglês para negócios   69.9      John Smith
5        Curso introdutório à programação com Python  99.90      João Silva

                     instrutor.email instrutor.telefone
0      joao.silva@emailaleatorio.com     (11) 9999-9999
1  maria.oliveira@emailaleatorio.com     (11) 8888-8888
2      ana.santos@emailaleatorio.com     (11) 7777-7777
3         contato@emailaleatorio.com
4
5      joao.silva@emailaleatorio.com     (11) 9999-9999

In [7]:
df.isnull().sum().sum()

np.int64(6)

In [8]:
#Percebemos, então, que existem pelo menos 6 valores
#nulos em nossa base de dados.
#Mas não necessariamente 6 amostras.
#Vamos verificar quais amostras são essas:
df[df.isna().any(axis=1)]

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
1,Excel para iniciantes,Produtividade,None,None,None,None,None,None,Maria Oliveira,maria.oliveira@emailaleatorio.com,(11) 8888-8888

O código df[df.isna().any(axis=1)] é utilizado para retornar um subconjunto do DataFrame df, contendo apenas as linhas que possuem pelo menos um valor ausente (NaN - Not a Number).

Para entender o código, vamos dividi-lo em partes:

df.isna() retorna um DataFrame com a mesma forma que df, contendo valores booleanos indicando quais elementos do DataFrame df são valores ausentes (NaN).
df.isna().any(axis=1) retorna uma série booleana que indica se cada linha do DataFrame df contém pelo menos um valor ausente. O parâmetro axis=1 indica que a verificação deve ser feita por linha.
df[df.isna().any(axis=1)] utiliza a série booleana retornada na etapa anterior como índice para o DataFrame df, retornando apenas as linhas que possuem pelo menos um valor ausente.

In [9]:
#realizar a remoção dessa amostra com o código:
df.dropna(inplace=True)

O trecho de código df.dropna(inplace=True) é utilizado para remover todas as linhas do DataFrame df que contenham valores ausentes (NaN - Not a Number). O parâmetro inplace=True é utilizado para indicar que a alteração deve ser feita diretamente no objeto DataFrame df sem criar uma cópia do DataFrame com as linhas removidas.

In [10]:
#Agora identificamos se
#há amostras duplicadas no conjunto de dados:
df.duplicated()

0    False
2    False
3    False
4    False
5     True
dtype: bool

In [11]:
#Percebemos que há uma amostra duplicada em nossa base
#de dados e que está presente no índice 5.
#Vamos remover essa amostra:
df.drop_duplicates(inplace=True)

O código df.drop_duplicates(inplace=True) é utilizado para remover as linhas duplicadas do DataFrame df. O parâmetro inplace=True é utilizado para indicar que a alteração deve ser feita diretamente no objeto DataFrame df sem criar uma cópia do DataFrame com as linhas duplicadas removidas. Já o método drop_duplicates() remove as linhas que têm exatamente os mesmos valores em todas as colunas, mantendo apenas a primeira ocorrência e descartando as duplicatas subsequentes.

In [12]:
#Vamos verificar onde tem amostras com strings vazias.
#Para isso, observamos duas colunas,
#começando pela coluna "instrutor.nome":
df[df['instrutor.nome'] == ""]

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
3,Inteligência artificial,Programação,40 horas,,2022-04-01,,Curso avançado sobre inteligência artificial c...,129.9,,contato@emailaleatorio.com,

In [13]:
#Agora vamos para a coluna "data_conclusao":
df[df['data_conclusao'] == ""]

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
3,Inteligência artificial,Programação,40 horas,,2022-04-01,,Curso avançado sobre inteligência artificial c...,129.9,,contato@emailaleatorio.com,
4,Inglês para negócios,Idiomas,20 horas,30,,,Curso de inglês para negócios,69.9,John Smith,,

Percebemos que, para verificar se há strings vazias em cada coluna, teríamos que fazer uma verificação manualmente. Para tornar esse processo mais automatizado, podemos fazer a substituição desses valores por NaN.

Dessa forma, podemos trabalhar com as strings vazias de forma mais fácil, utilizando os métodos do Pandas que são projetados para lidar com valores nulos, como o método dropna. Esse método nos permite eliminar linhas ou colunas que contenham valores nulos, o que pode ser muito útil para limpar os dados e garantir que eles estejam prontos para serem analisados.

In [14]:
# Substitui strings vazias por valores nulos
df.replace('', pd.NA, inplace=True)

In [15]:
df.dropna(inplace=True)
print(df)

                             curso    categoria carga_horaria concluintes  \
0         Introdução à programação  Programação      20 horas         100
2  Marketing digital para negócios    Marketing      30 horas          75

  data_inicio data_conclusao                                    descricao  \
0  2022-01-01     2022-01-20  Curso introdutório à programação com Python
2  2022-03-01     2022-03-31              Curso introdutório em marketing

   preco instrutor.nome                instrutor.email instrutor.telefone
0  99.90     João Silva  joao.silva@emailaleatorio.com     (11) 9999-9999
2   89.9     Ana Santos  ana.santos@emailaleatorio.com     (11) 7777-7777

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 0 to 2
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   curso               2 non-null      object
 1   categoria           2 non-null      object
 2   carga_horaria       2 non-null      object
 3   concluintes         2 non-null      object
 4   data_inicio         2 non-null      object
 5   data_conclusao      2 non-null      object
 6   descricao           2 non-null      object
 7   preco               2 non-null      object
 8   instrutor.nome      2 non-null      object
 9   instrutor.email     2 non-null      object
 10  instrutor.telefone  2 non-null      object
dtypes: object(11)
memory usage: 192.0+ bytes

In [17]:
# Converte a concluintes para o tipo inteiro
df['concluintes'] = df['concluintes'].astype(int)

# Converte a coluna data_inicio e data_conclusao para o tipo datetime
df['data_inicio'] = pd.to_datetime(df['data_inicio'])
df['data_conclusao'] = pd.to_datetime(df['data_conclusao'])

# Convertendo a coluna preço para o tipo float
df['preco'] = df['preco'].astype(float)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 0 to 2
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   curso               2 non-null      object
 1   categoria           2 non-null      object
 2   carga_horaria       2 non-null      object
 3   concluintes         2 non-null      int64
 4   data_inicio         2 non-null      datetime64[ns]
 5   data_conclusao      2 non-null      datetime64[ns]
 6   descricao           2 non-null      object
 7   preco               2 non-null      float64
 8   instrutor.nome      2 non-null      object
 9   instrutor.email     2 non-null      object
 10  instrutor.telefone  2 non-null      object
dtypes: datetime64[ns](2), float64(1), int64(1), object(7)
memory usage: 192.0+ bytes